// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DestroyClient() {
  return window['go']['main']['App']['DestroyClient']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NewClient(arg1, arg2) {
  return window['go']['main']['App']['NewClient'](arg1, arg2);
}

export function Receive() {
  return window['go']['main']['App']['Receive']();
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
