// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DestroyClient():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function NewClient(arg1:string,arg2:string):Promise<boolean>;

export function Receive():Promise<void>;

export function Send(arg1:string):Promise<void>;
