name: Build Wails App on Multiple Platforms

permissions:
  contents: write

env:
  APP_NAME: ChatApp

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        build:
          - name: 'ChatApp-linux'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'ChatApp-windows.exe'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'ChatApp-mac'
            platform: 'darwin/universal'
            os: 'macos-latest'
        go-version: [1.24.1]
        node-version: [22.x]

    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails App
        run: |
          pwd
          wails build --platform ${{ matrix.build.platform }} -o ${{ matrix.build.name }}

      - name: Build .app zip file
        if: runner.os == 'macOS'
        shell: bash
        run: |
          pwd
          ditto -c -k --keepParent ./build/bin/${{ env.APP_NAME }}.app ./build/bin/${{ matrix.build.name }}.app.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wails-Build-${{ matrix.build.name }}
          path: build/bin/